#!/usr/bin/env Rscript
# ============================================================================
# CCLE/DepMap — PRISM SMAC-mimetic AUC vs SecB polarization   [PLACEHOLDER]
# ----------------------------------------------------------------------------
# *** PLACEHOLDER PANEL — final figure/panel letter NOT yet assigned. ***
# Slated as a supplementary / mechanistic side-quest. Rename this directory +
# scripts and set MANUSCRIPT PANEL(S) once the panel is decided. See
# ./README.md and the source module
# ../../2026_final_xenium_analysis/davids side quests/ccle_depmap/.
#
# PURPOSE
#   THE HEADLINE of this module. PRISM Repurposing Harmonized 25Q2 viability-AUC
#   cross-check for SMAC mimetics (LCL-161, birinapant, GDC-0152) vs SecB
#   polarization across HGSC cell lines. Lower AUC = more sensitive; the result
#   is that SecB-polarized HGSC lines are SELECTIVELY SENSITIVE to SMAC mimetics
#   (negative Spearman rho), while chemotherapy negative controls (carboplatin,
#   doxorubicin, etc.) do NOT show the pattern. Small-n exact Spearman is used.
#
# INPUTS
#   cfg_obj("ccle_line_scores")        -> hgsc_line_scores.tsv (deposited per-line
#                                          scores; regenerated by 01_score_hgsc_lines.R)
#   cfg_obj("ccle_prism_auc")          -> REPURPOSINGAUCMatrix.csv
#   cfg_obj("ccle_prism_conditions")   -> REPURPOSINGCollapsedConditions.csv (compound meta)
#   Shared helpers: config/config.R
#
# OUTPUTS (all via cfg_path("figures_dir","figure_ccle_smac_mimetics", ...))
#   smac_mimetic_correlations.tsv      (SMAC + negative-control AUC correlations)
#   smac_combined_panel.pdf            (THE headline figure: 3-SMAC facet panel)
#   smac_lead_scatter.pdf              (lead = broadest-coverage SMAC compound)
#   scatter_<COMPOUND>.pdf             (per-SMAC scatter; e.g. scatter_LCL_161.pdf)
#
# MANUSCRIPT PANEL(S): TBD (placeholder — supplementary / mechanistic; panel not yet assigned)
# RUNTIME TIER: fast (small HGSC subset; exact Spearman on n<=12)
# ============================================================================

.here <- dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]))
if (is.na(.here) || !nzchar(.here)) .here <- getwd()
source(file.path(.here, "..", "..", "config", "config.R"))

set.seed(CFG$seed)

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(ggrepel)
  library(dplyr)
})

FIG_DIR <- cfg_path("figures_dir", "figure_ccle_smac_mimetics")

# ---- load scored lines ------------------------------------------------------
scores <- fread(cfg_obj("ccle_line_scores"))
perm_ids   <- scores[in_permissive == TRUE, ModelID]
strict_ids <- scores[in_strict == TRUE,     ModelID]

# ---- load PRISM AUC matrix --------------------------------------------------
cat("Loading PRISM AUC matrix...\n")
auc <- fread(cfg_obj("ccle_prism_auc"))
setnames(auc, 1, "ModelID")
cat(sprintf("AUC matrix: %d models x %d compounds\n", nrow(auc), ncol(auc) - 1L))

# ---- compound metadata: build DPC-ID -> CompoundName mapping ---------------
cond <- fread(cfg_obj("ccle_prism_conditions"))
cname_map <- unique(cond[, .(CompoundID, CompoundName)])
cname_map <- cname_map[!duplicated(CompoundID)]

# Find SMAC mimetics
smac_targets <- c("LCL-161","LCL161","BIRINAPANT","TL32711","GDC-0152","AT-406",
                  "DEBIO-1143","XEVINAPANT","EMBELIN")
norm <- function(x) toupper(gsub("[- _]","", x))
smac_hits <- cname_map[norm(CompoundName) %in% norm(smac_targets)]
cat("\nSMAC mimetic compounds matched in PRISM:\n")
print(smac_hits)

# Add a few negative-control compounds (chemotherapy / unrelated targets)
neg_targets <- c("PACLITAXEL","CISPLATIN","CARBOPLATIN","ETOPOSIDE",
                 "DOXORUBICIN","DMSO")
neg_hits <- cname_map[norm(CompoundName) %in% norm(neg_targets)]
cat("\nNegative-control compounds:\n")
print(neg_hits)

# ---- subset AUC matrix to HGSC lines + target compounds --------------------
all_target_ids <- c(smac_hits$CompoundID, neg_hits$CompoundID)
all_target_ids <- intersect(all_target_ids, colnames(auc))
cat(sprintf("Of %d target compounds, %d have PRISM AUC data\n",
            length(c(smac_hits$CompoundID, neg_hits$CompoundID)),
            length(all_target_ids)))

# Subset to HGSC permissive lines
auc_hgsc <- auc[ModelID %in% perm_ids]
cat(sprintf("HGSC lines with PRISM data: %d/%d\n",
            nrow(auc_hgsc), length(perm_ids)))

# Merge with polarization
auc_hgsc <- merge(auc_hgsc,
                  scores[, .(ModelID, StrippedCellLineName, polarization,
                             polarization_UCell, in_strict)],
                  by = "ModelID")

# ---- correlation for each target compound ----------------------------------
get_cname <- function(cid) {
  m <- cname_map[CompoundID == cid, CompoundName]
  if (length(m)) m[1] else cid
}

cor_table <- rbindlist(lapply(all_target_ids, function(cid) {
  y <- auc_hgsc[[cid]]
  if (is.null(y)) return(NULL)
  ok <- !is.na(y)
  if (sum(ok) < 4) {
    return(data.table(CompoundID = cid, CompoundName = get_cname(cid),
                      n = sum(ok), rho = NA, p = NA,
                      rho_UCell = NA, p_UCell = NA))
  }
  # Use exact = TRUE for small-n SMAC data (n<=12); fall back to asymptotic
  # if ties prevent exact computation
  ct  <- suppressWarnings(cor.test(auc_hgsc$polarization[ok], y[ok],
                                   method = "spearman", exact = TRUE))
  ctu <- suppressWarnings(cor.test(auc_hgsc$polarization_UCell[ok], y[ok],
                                   method = "spearman", exact = TRUE))
  data.table(CompoundID = cid, CompoundName = get_cname(cid),
             n = sum(ok),
             rho = unname(ct$estimate),  p = ct$p.value,
             rho_UCell = unname(ctu$estimate), p_UCell = ctu$p.value)
}))

cor_table[, padj := p.adjust(p, method = "BH")]
cor_table[, is_smac := CompoundID %in% smac_hits$CompoundID]
cor_table <- cor_table[order(is_smac, decreasing = TRUE)][order(rho)]

fwrite(cor_table, file.path(FIG_DIR, "smac_mimetic_correlations.tsv"), sep = "\t")
cat("\n=== SMAC mimetic + negative control AUC correlations ===\n")
print(cor_table)

# ---- pick lead compound (max coverage among SMAC) --------------------------
smac_rows <- cor_table[is_smac == TRUE]
lead <- smac_rows[which.max(n)]
cat(sprintf("\nLead SMAC mimetic: %s (n=%d, rho=%.2f, p=%.3g)\n",
            lead$CompoundName, lead$n, lead$rho, lead$p))

# ---- scatter plot for lead compound ----------------------------------------
plot_scatter <- function(cid, cname) {
  y <- auc_hgsc[[cid]]
  dat <- auc_hgsc[, .(StrippedCellLineName, polarization, in_strict)]
  dat$auc <- y
  dat <- dat[!is.na(auc)]
  ct <- suppressWarnings(cor.test(dat$polarization, dat$auc, method = "spearman", exact = TRUE))
  ggplot(dat, aes(x = polarization, y = auc)) +
    geom_smooth(method = "lm", se = TRUE, colour = "grey40",
                fill = "grey80", linewidth = 0.4) +
    geom_point(aes(colour = in_strict), size = 2.5) +
    geom_text_repel(aes(label = StrippedCellLineName), size = 2.5,
                    max.overlaps = Inf, segment.size = 0.2) +
    scale_colour_manual(values = c(`FALSE` = "grey60", `TRUE` = "#d7191c"),
                        labels = c("permissive only", "Domcke-9 strict"),
                        name = NULL) +
    labs(x = "SecB polarization (z-mean)",
         y = sprintf("%s AUC (higher = less sensitive)", cname),
         title = sprintf("%s viability AUC vs SecB polarization", cname),
         subtitle = sprintf("PRISM Harmonized 25Q2; n=%d HGSC; Spearman rho=%.2f, exact p=%.3g",
                            nrow(dat), unname(ct$estimate), ct$p.value)) +
    theme_classic(base_size = 9)
}

if (nrow(smac_rows) > 0) {
  for (i in seq_len(nrow(smac_rows))) {
    cid <- smac_rows$CompoundID[i]
    cname <- smac_rows$CompoundName[i]
    p <- plot_scatter(cid, cname)
    safename <- gsub("[^A-Za-z0-9]","_", cname)
    ggsave(file.path(FIG_DIR, sprintf("scatter_%s.pdf", safename)),
           p, width = 5.5, height = 4.5)
  }
  p_lead <- plot_scatter(lead$CompoundID, lead$CompoundName)
  ggsave(file.path(FIG_DIR, "smac_lead_scatter.pdf"), p_lead,
         width = 5.5, height = 4.5)
}

# ---- combined panel for the 3 SMAC mimetics (THE headline figure) ----------
if (nrow(smac_rows) > 1) {
  long <- rbindlist(lapply(seq_len(nrow(smac_rows)), function(i) {
    cid <- smac_rows$CompoundID[i]
    cname <- smac_rows$CompoundName[i]
    y <- auc_hgsc[[cid]]
    d <- auc_hgsc[, .(StrippedCellLineName, polarization, in_strict)]
    d[, compound := cname]
    d[, auc := y]
    d[!is.na(auc)]
  }))
  long[, compound := factor(compound, levels = smac_rows$CompoundName)]
  # Annotate per-facet rho
  ann <- smac_rows[, .(compound = CompoundName,
                       label = sprintf("rho = %.2f\np = %.3g\nn = %d", rho, p, n))]
  ann[, compound := factor(compound, levels = smac_rows$CompoundName)]
  p_combo <- ggplot(long, aes(x = polarization, y = auc)) +
    geom_smooth(method = "lm", se = TRUE, colour = "grey40",
                fill = "grey80", linewidth = 0.4) +
    geom_point(aes(colour = in_strict), size = 2) +
    geom_text_repel(aes(label = StrippedCellLineName), size = 2,
                    max.overlaps = Inf, segment.size = 0.15) +
    geom_text(data = ann, aes(x = -Inf, y = Inf, label = label),
              hjust = -0.1, vjust = 1.2, size = 2.5) +
    scale_colour_manual(values = c(`FALSE` = "grey60", `TRUE` = "#d7191c"),
                        labels = c("permissive", "Domcke-9 strict"),
                        name = NULL) +
    facet_wrap(~ compound, scales = "free_y", ncol = 3) +
    labs(x = "SecB polarization (z-mean)", y = "PRISM AUC",
         title = "SMAC mimetic viability AUC vs SecB polarization (HGSC)",
         subtitle = "PRISM Repurposing Harmonized 25Q2") +
    theme_classic(base_size = 8)
  ggsave(file.path(FIG_DIR, "smac_combined_panel.pdf"), p_combo,
         width = 10, height = 4.5)
}

cat("\nDone. [PLACEHOLDER — assign panel letter, then rename per ./README.md]\n")
