#!/usr/bin/env Rscript
# ============================================================================
# CCLE/DepMap — targeted NF-kB / BIRC3 / IAP Chronos vs polarization   [PLACEHOLDER]
# ----------------------------------------------------------------------------
# *** PLACEHOLDER PANEL — final figure/panel letter NOT yet assigned. ***
# Slated as a supplementary / mechanistic side-quest. Rename this directory +
# scripts and set MANUSCRIPT PANEL(S) once the panel is decided. See
# ./README.md and the source module
# ../../2026_final_xenium_analysis/davids side quests/ccle_depmap/.
#
# PURPOSE
#   SUPPORT for the script-02 PRISM headline. Targeted NF-kB / BIRC3 / IAP /
#   hypoxia panel (27 genes) Chronos dependency vs SecB polarization across HGSC
#   lines (permissive + strict Domcke-9). The pre-specified single-gene BIRC3
#   test is NULL / opposite-direction (rho = +0.22) — interpreted as IAP-family
#   redundancy (cIAP1/cIAP2/XIAP) that pan-IAP SMAC mimetics bypass. The upstream
#   non-redundant TNF-receptor-signalosome adapter TRAF2 trends in the predicted
#   direction (rho = -0.45, p = 0.08), consistent with the SMAC-mimetic signal.
#
# INPUTS
#   cfg_obj("ccle_line_scores")  -> hgsc_line_scores.tsv (deposited per-line
#                                    scores; regenerated by 01_score_hgsc_lines.R)
#   cfg_obj("ccle_crispr")       -> CRISPRGeneEffect.csv (Chronos dependency, ~430 MB)
#   Shared helpers: config/config.R
#
# OUTPUTS (all via cfg_path("figures_dir","figure_ccle_smac_mimetics", ...))
#   nfkb_panel_correlations.tsv          (per-gene Spearman; permissive + strict)
#   forest_nfkb_panel.pdf                (forest of permissive correlations)
#   scatter_BIRC3_polarization.pdf       (BIRC3 scatter; permissive)
#   scatter_BIRC3_polarization_strict.pdf(BIRC3 scatter; Domcke-9 strict)
#   scatter_<GENE>_polarization.pdf      (top gene by p_zmean; yields TRAF2)
#
# MANUSCRIPT PANEL(S): TBD (placeholder — supplementary / mechanistic; panel not yet assigned)
# RUNTIME TIER: moderate (loads the ~430 MB Chronos matrix; fast correlations)
# ============================================================================

.here <- dirname(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]))
if (is.na(.here) || !nzchar(.here)) .here <- getwd()
source(file.path(.here, "..", "..", "config", "config.R"))

set.seed(CFG$seed)

suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(ggrepel)
  library(dplyr)
})

FIG_DIR <- cfg_path("figures_dir", "figure_ccle_smac_mimetics")

# ---- load scored HGSC lines --------------------------------------------------
scores <- fread(cfg_obj("ccle_line_scores"))
cat(sprintf("Scored HGSC lines: %d (permissive); %d in strict Domcke-9\n",
            sum(scores$in_permissive), sum(scores$in_strict)))

# ---- load Chronos matrix -----------------------------------------------------
cat("\nLoading CRISPRGeneEffect.csv (~430 MB)...\n")
chrn <- fread(cfg_obj("ccle_crispr"))
setnames(chrn, 1, "ModelID")
cat(sprintf("Chronos: %d models x %d genes\n", nrow(chrn), ncol(chrn) - 1L))

# Parse gene symbols (column format: 'SYMBOL (entrezID)')
gene_syms <- sub("\\s*\\(.+\\)\\s*$", "", colnames(chrn)[-1])
# Map full column name to symbol
sym2col <- setNames(colnames(chrn)[-1], gene_syms)

# ---- targeted NF-kB / BIRC3 panel --------------------------------------------
panel <- c(
  # IAP family
  "BIRC3","BIRC2","XIAP","BIRC5",
  # NF-kB core
  "RELA","RELB","NFKB1","NFKB2","REL",
  # NF-kB upstream
  "IKBKB","CHUK","IKBKG","MAP3K7","MAP3K14","TRAF2","TRAF6",
  # Receptor / ligand axis
  "TNFRSF1A","TNFRSF1B","TNFRSF10A","TNFRSF10B",
  # Hypoxia
  "HIF1A","EPAS1","ARNT",
  # Survival controls
  "BCL2","MCL1",
  # Other
  "NFKBIA","ICAM1"
)
present <- intersect(panel, gene_syms)
missing <- setdiff(panel, gene_syms)
cat(sprintf("\nPanel coverage: %d/%d genes present (missing: %s)\n",
            length(present), length(panel),
            paste(missing, collapse = ",")))

# Subset Chronos to panel + HGSC lines (permissive set)
permissive_ids <- scores[in_permissive == TRUE, ModelID]
strict_ids     <- scores[in_strict == TRUE,     ModelID]

# Build a tidy long table: ModelID, gene, chronos
chrn_perm <- chrn[ModelID %in% permissive_ids]
cat(sprintf("HGSC permissive lines with Chronos: %d/%d\n",
            nrow(chrn_perm), length(permissive_ids)))
missing_chrn <- setdiff(permissive_ids, chrn_perm$ModelID)
if (length(missing_chrn)) {
  cat("Lines missing Chronos:\n")
  print(scores[ModelID %in% missing_chrn, .(StrippedCellLineName, ModelID)])
}

# Subset matrix to panel
panel_cols <- sym2col[present]
sub <- chrn_perm[, c("ModelID", panel_cols), with = FALSE]
setnames(sub, c("ModelID", present))

# Merge with polarization
sub <- merge(sub, scores[, .(ModelID, StrippedCellLineName, polarization,
                             polarization_UCell, in_strict)],
             by = "ModelID")

# ---- per-gene Spearman correlations -----------------------------------------
do_cor <- function(x, y) {
  ok <- !is.na(x) & !is.na(y)
  if (sum(ok) < 4) return(list(rho = NA, p = NA, n = sum(ok)))
  ct <- suppressWarnings(cor.test(x[ok], y[ok], method = "spearman", exact = FALSE))
  list(rho = unname(ct$estimate), p = ct$p.value, n = sum(ok))
}

# Permissive set
res_perm <- rbindlist(lapply(present, function(g) {
  r <- do_cor(sub[[g]], sub$polarization)
  ru <- do_cor(sub[[g]], sub$polarization_UCell)
  data.table(gene = g,
             rho_zmean = r$rho, p_zmean = r$p,
             rho_UCell = ru$rho, p_UCell = ru$p,
             n = r$n)
}))
res_perm[, padj_zmean := p.adjust(p_zmean, method = "BH")]
res_perm[, padj_UCell := p.adjust(p_UCell, method = "BH")]
res_perm[, set := "permissive"]

# Strict set
sub_strict <- sub[in_strict == TRUE]
res_strict <- rbindlist(lapply(present, function(g) {
  r <- do_cor(sub_strict[[g]], sub_strict$polarization)
  ru <- do_cor(sub_strict[[g]], sub_strict$polarization_UCell)
  data.table(gene = g,
             rho_zmean = r$rho, p_zmean = r$p,
             rho_UCell = ru$rho, p_UCell = ru$p,
             n = r$n)
}))
res_strict[, padj_zmean := p.adjust(p_zmean, method = "BH")]
res_strict[, padj_UCell := p.adjust(p_UCell, method = "BH")]
res_strict[, set := "strict"]

res <- rbind(res_perm, res_strict)
fwrite(res, file.path(FIG_DIR, "nfkb_panel_correlations.tsv"), sep = "\t")

cat("\n=== Permissive set (n=", nrow(sub), ") ===\n", sep = "")
print(res_perm[order(rho_zmean)])

cat("\n=== Strict Domcke-9 set (n=", nrow(sub_strict), ") ===\n", sep = "")
print(res_strict[order(rho_zmean)])

# Focused report on BIRC3
cat("\n=== BIRC3 focused ===\n")
print(res[gene == "BIRC3"])

# ---- forest plot of permissive correlations ----------------------------------
# Reorder genes by rho
fp <- copy(res_perm)
fp[, gene := factor(gene, levels = gene[order(rho_zmean)])]
# 95% CI via Fisher z
fp[, z := 0.5 * log((1 + rho_zmean) / (1 - rho_zmean))]
fp[, se := 1 / sqrt(n - 3)]
fp[, lo := tanh(z - 1.96 * se)]
fp[, hi := tanh(z + 1.96 * se)]

p_fp <- ggplot(fp, aes(x = rho_zmean, y = gene)) +
  geom_vline(xintercept = 0, linetype = "dashed", colour = "grey50") +
  geom_errorbarh(aes(xmin = lo, xmax = hi), height = 0, colour = "grey50") +
  geom_point(aes(fill = padj_zmean < 0.1), shape = 21, size = 3) +
  scale_fill_manual(values = c(`FALSE` = "white", `TRUE` = "#d7191c"),
                    name = "BH q < 0.1") +
  scale_x_continuous(limits = c(-1, 1), breaks = seq(-1, 1, by = 0.5)) +
  labs(x = "Spearman rho (polarization vs Chronos)",
       y = NULL,
       title = "NF-kB / BIRC3 axis Chronos correlation with polarization",
       subtitle = sprintf("DepMap 24Q4 HGSC, permissive set (n=%d)", nrow(sub))) +
  theme_classic(base_size = 9)

ggsave(file.path(FIG_DIR, "forest_nfkb_panel.pdf"), p_fp,
       width = 5.5, height = 6)

# ---- BIRC3 scatter ----------------------------------------------------------
plot_scatter <- function(gene_name, set_filter = NULL, suffix = "") {
  dat <- copy(sub)
  if (!is.null(set_filter)) dat <- dat[get(set_filter) == TRUE]
  dat[, gene_chronos := get(gene_name)]
  ct <- cor.test(dat$gene_chronos, dat$polarization, method = "spearman", exact = FALSE)
  ggplot(dat, aes(x = polarization, y = gene_chronos)) +
    geom_hline(yintercept = 0, linetype = "dotted", colour = "grey50") +
    geom_smooth(method = "lm", se = TRUE, colour = "grey40",
                fill = "grey80", linewidth = 0.4) +
    geom_point(aes(colour = in_strict), size = 2.5) +
    geom_text_repel(aes(label = StrippedCellLineName), size = 2.5,
                    max.overlaps = Inf, segment.size = 0.2) +
    scale_colour_manual(values = c(`FALSE` = "grey60", `TRUE` = "#d7191c"),
                        labels = c("permissive only", "Domcke-9 strict"),
                        name = NULL) +
    labs(x = "SecB polarization (z-mean)",
         y = sprintf("%s Chronos (more neg = more essential)", gene_name),
         title = sprintf("%s dependency vs SecB polarization", gene_name),
         subtitle = sprintf("n=%d HGSC; Spearman rho = %.2f, p = %.3g",
                            nrow(dat), unname(ct$estimate), ct$p.value)) +
    theme_classic(base_size = 9)
}

p_b3 <- plot_scatter("BIRC3")
ggsave(file.path(FIG_DIR, "scatter_BIRC3_polarization.pdf"), p_b3,
       width = 5.5, height = 4.5)

p_b3_str <- plot_scatter("BIRC3", set_filter = "in_strict",
                         suffix = "_strict")
ggsave(file.path(FIG_DIR, "scatter_BIRC3_polarization_strict.pdf"), p_b3_str,
       width = 5.5, height = 4.5)

# Also plot the top significant gene by p_zmean (if any) -> yields TRAF2
sig <- res_perm[order(p_zmean)][1]
if (!is.na(sig$rho_zmean)) {
  cat(sprintf("\nTop-ranked gene by p_zmean: %s (rho=%.2f, p=%.3g)\n",
              sig$gene, sig$rho_zmean, sig$p_zmean))
  p_top <- plot_scatter(sig$gene)
  ggsave(file.path(FIG_DIR,
                   sprintf("scatter_%s_polarization.pdf", sig$gene)),
         p_top, width = 5.5, height = 4.5)
}

cat("\nDone. [PLACEHOLDER — assign panel letter, then rename per ./README.md]\n")
