#!/usr/bin/env python3
"""
SF11 — Secretory polarization score across the Xenium cohort (3 cohorts)
========================================================================

Purpose
    Per-sample violin strip of secretory polarization (SecB_UCell − SecA_UCell)
    across the full Xenium spatial cohort, with one violin per sample/patient,
    all mixed on a single x-axis and sorted left→right by ascending median
    polarization ("SecA → SecB"). Violins are coloured by cohort:
        - Fallopian tube cores       (n=13, orange  #E07850)
        - HGSC whole-tissue samples  (n=8,  purple  #8A5DAF)
        - HGSC tissue microarray     (n=97, beige   #D4A574)
    TMA cores from the same patient are pooled into a single violin (matching
    the published per-patient grouping). Median-only marker per violin (the
    strip is far too dense for boxplots). Dashed reference lines mark the
    TMA-internal median polarization of SecA / Intermediate / SecB cells.

    This reproduces the published Supplemental Figure 11 (a 3-cohort per-sample
    distribution), replacing the earlier atlas + whole-tissue strip. There is no
    atlas component in the published panel.

INPUTS
    data_root/2026_final_xenium_analysis/output/06f_reclassification_polarization/
        reclassified_xenium_scores.csv
        (per-cell polarization_UCell + cell_label_06f; whole-tissue 'sfe_*'
         samples and the pooled TMA 'sfe_tma'. Deposited cache, read-only.)
    output_root/metadata/tma_barcode_patient_map.csv
        (TMA barcode -> patient_id / sample_type; assigns each TMA cell to the
         Fallopian-tube or HGSC-TMA cohort and to a patient. Regenerated by
         figures/_prep/01_export_tma_barcode_patient_map.py — the same map the
         Fig 4A/B composition dendrogram consumes.)

OUTPUTS
    output_root/figures/supplementary/SF11_xenium_polarization_per_sample.{png,svg}

MANUSCRIPT PANEL(S)
    SF11.

RUNTIME TIER
    fast (reads one score CSV + one barcode map; pooled per-sample violins).

CACHE CONTRACT
    The 06f score CSV is the deposited copy under data_root and is read-only
    here. The TMA barcode->patient map is read from output_root/metadata/ and is
    regenerated by figures/_prep/01_export_tma_barcode_patient_map.py.
"""

import os
import sys
import time

import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Patch

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
from config.config import path, CFG  # noqa: E402

# ---------- Paths (central config) ----------
XEN_CSV = path("data_root", "2026_final_xenium_analysis", "output",
               "06f_reclassification_polarization", "reclassified_xenium_scores.csv")
BC_MAP = path("output_root", "metadata", "tma_barcode_patient_map.csv")

STEM = "SF11_xenium_polarization_per_sample"
OUT_PNG = path("output_root", "figures", "supplementary", f"{STEM}.png")
OUT_SVG = path("output_root", "figures", "supplementary", f"{STEM}.svg")

# ---------- Cohort colours (match the Fig 4A/B composition dendrogram) ----------
FTE_COLOR = "#E07850"   # Fallopian tube (ciliated orange)
WT_COLOR = "#8A5DAF"    # HGSC whole tissue (purple)
TMA_COLOR = "#D4A574"   # HGSC TMA (beige)
TISSUE_COLOR = {
    "Fallopian tube":    FTE_COLOR,
    "HGSC whole tissue": WT_COLOR,
    "HGSC TMA":          TMA_COLOR,
}

# Reference lines = TMA-internal median polarization per cell class.
# Label standardized "Transitioning" -> "Intermediate".
REF_LABELS = ["SecA epithelium", "Transitioning epithelium", "SecB epithelium"]
REF_SHORT = {
    "SecA epithelium":          "SecA",
    "Transitioning epithelium": "Int",
    "SecB epithelium":          "SecB",
}
REF_COLOR = {
    "SecA epithelium":          "#E6A141",
    "Transitioning epithelium": "#C08E48",
    "SecB epithelium":          "#9A7D55",
}

# Pooled whole-tissue cohort (the published 8); drop the 2 post-preprint FTE
# whole-tissue samples (FT1-1, EAOC-1-FTE) that leak through the un-pinned cache.
WT_SAMPLES = ["sfe_" + s for s in CFG["cohort"]["whole_tissue"]]

MIN_CELLS = 10   # minimum secretory cells for a sample/patient to be plotted

# ---------- Font sizes ----------
FA, FK, FN = 6, 5.5, 5

plt.rcParams.update({
    "font.family":       "sans-serif",
    "font.sans-serif":   ["Arial", "Helvetica", "DejaVu Sans"],
    "font.size":         FA,
    "axes.titlesize":    FA,
    "axes.labelsize":    FA,
    "xtick.labelsize":   FK,
    "ytick.labelsize":   FK,
    "legend.fontsize":   FN,
    "figure.dpi":        450,
    "savefig.dpi":       450,
    "pdf.fonttype":      42,
    "ps.fonttype":       42,
    "svg.fonttype":      "none",
    "savefig.bbox":      "tight",
    "axes.linewidth":    0.4,
    "xtick.major.width": 0.4,
    "ytick.major.width": 0.4,
})


def draw_violin_medianline(ax, data_list, positions, fills, w=0.95, alpha=0.85):
    """Filled violins (coloured by cohort) with a short median tick each."""
    vp = ax.violinplot(data_list, positions=positions,
                       showmeans=False, showmedians=False, showextrema=False,
                       widths=w)
    for body, c in zip(vp["bodies"], fills):
        body.set_facecolor(c)
        body.set_edgecolor("none")
        body.set_linewidth(0)
        body.set_alpha(alpha)
    for pos, d in zip(positions, data_list):
        med = np.median(d)
        ax.plot([pos - w / 3, pos + w / 3], [med, med],
                color="black", lw=0.5, zorder=5)


def main():
    t0 = time.time()
    print("=" * 72)
    print(f"  {STEM}")
    print("=" * 72)

    # ---- Per-cell polarization (06f) ----
    xen = pd.read_csv(XEN_CSV, usecols=["sample", "barcode_orig",
                                        "polarization_UCell", "cell_label_06f"])

    # ---- TMA cells -> patient_id + sample_type (Fallopian tube vs HGSC TMA) ----
    tma = xen[xen["sample"] == "sfe_tma"].copy()
    bc = pd.read_csv(BC_MAP)
    tma = tma.merge(bc[["barcode_orig", "patient_id", "sample_type"]],
                    on="barcode_orig", how="left")
    tma = tma[tma["patient_id"].notna()].copy()
    tma["patient_id"] = tma["patient_id"].astype(int).astype(str)
    ft = tma[tma["sample_type"] == "fallopian"].copy()   # Fallopian tube cores
    tu = tma[tma["sample_type"] == "tumour"].copy()       # HGSC TMA tumour cores

    # ---- Whole-tissue cells (the published 8 samples) ----
    wt = xen[xen["sample"].isin(WT_SAMPLES)].copy()
    leaked = set(["sfe_" + s for s in CFG["cohort"]["fte_exclude_wt"]]) & set(wt["sample"])
    assert not leaked, f"FTE whole-tissue sample leaked into the WT arm: {leaked}"

    print(f"   Fallopian tube:    {len(ft):>9,} cells, {ft['patient_id'].nunique()} cores")
    print(f"   HGSC whole tissue: {len(wt):>9,} cells, {wt['sample'].nunique()} samples")
    print(f"   HGSC TMA:          {len(tu):>9,} cells, {tu['patient_id'].nunique()} patients")

    # ---- Reference: TMA-internal median polarization per cell class ----
    ref_med = {}
    for label in REF_LABELS:
        vals = tu.loc[tu["cell_label_06f"] == label, "polarization_UCell"]
        if len(vals) > 0:
            ref_med[label] = float(vals.median())
            print(f"   Ref {REF_SHORT[label]:>5s} ({label:26s}) = {ref_med[label]:.4f}")

    # ---- Build per-unit list (FTE/TMA grouped by patient; WT by sample) ----
    units = []   # (values, cohort_label)

    def add_grouped(df, key, cohort):
        n = 0
        for g, sub in df.groupby(key):
            vals = sub["polarization_UCell"].values
            if len(vals) >= MIN_CELLS:
                units.append((vals, cohort))
                n += 1
        return n

    n_ft = add_grouped(ft, "patient_id", "Fallopian tube")
    n_wt = add_grouped(wt, "sample", "HGSC whole tissue")
    n_tu = add_grouped(tu, "patient_id", "HGSC TMA")
    print(f"   Plotted units: {n_ft} FTE + {n_wt} WT + {n_tu} TMA = {len(units)}")

    # ---- Sort all units by median polarization (low -> high) ----
    units.sort(key=lambda u: np.median(u[0]))
    all_data = [u[0] for u in units]
    all_fills = [TISSUE_COLOR[u[1]] for u in units]
    n_all = len(units)
    positions = np.arange(n_all) + 1

    # ============================================================
    # FIGURE — full letter width, compact height
    # ============================================================
    fig, ax = plt.subplots(figsize=(8.5, 2.2))

    xlo = positions[0] - 0.8
    xhi = positions[-1] + 2.5

    # Zero line
    ax.axhline(0, color="black", lw=0.4, ls="-", alpha=0.3, zorder=0)

    # Reference dashed lines + right-side labels
    for label in REF_LABELS:
        if label in ref_med:
            ax.axhline(ref_med[label], color=REF_COLOR[label],
                       lw=0.6, ls=(0, (4, 2)), alpha=0.85, zorder=0)
            ax.text(xhi - 0.1, ref_med[label], REF_SHORT[label],
                    ha="right", va="bottom", fontsize=FN, color=REF_COLOR[label])

    # All violins (median tick only; the strip is too dense for boxes)
    draw_violin_medianline(ax, all_data, positions, all_fills)

    # Direction arrow ("SecA -> SecB")
    center = (positions[0] + positions[-1]) / 2
    ax.annotate("", xy=(positions[-1], -0.07), xytext=(positions[0], -0.07),
                xycoords=("data", "axes fraction"),
                textcoords=("data", "axes fraction"),
                arrowprops=dict(arrowstyle="->", color="grey", lw=0.6))
    ax.text(center, -0.10, "SecA → SecB", color="grey", fontsize=FN - 1,
            ha="center", va="top", style="italic",
            transform=ax.get_xaxis_transform())

    # Cohort legend
    handles = [
        Patch(facecolor=FTE_COLOR, edgecolor="none", label=f"Fallopian tube (n={n_ft})"),
        Patch(facecolor=WT_COLOR, edgecolor="none", label=f"HGSC whole tissue (n={n_wt})"),
        Patch(facecolor=TMA_COLOR, edgecolor="none", label=f"HGSC TMA (n={n_tu})"),
    ]
    ax.legend(handles=handles, loc="upper left", frameon=False, fontsize=FN,
              handlelength=1.2, handleheight=0.8, borderpad=0.3, labelspacing=0.3)

    # Axes
    ax.set_xticks([])
    ax.set_xlim(xlo, xhi)
    ax.set_ylabel("Secretory polarization (SecB − SecA)")
    ax.set_ylim(-0.45, 0.45)
    for s in ("top", "right", "bottom"):
        ax.spines[s].set_visible(False)
    ax.spines["left"].set_linewidth(0.4)
    ax.tick_params(axis="y", length=2, width=0.4)
    ax.tick_params(axis="x", length=0)

    fig.tight_layout(pad=0.5)
    fig.savefig(OUT_PNG, format="png", dpi=450, bbox_inches="tight")
    fig.savefig(OUT_SVG, format="svg", bbox_inches="tight")
    plt.close(fig)

    print(f"   -> {OUT_PNG}")
    print(f"   -> {OUT_SVG}")
    print(f"Done in {time.time()-t0:.1f}s")


if __name__ == "__main__":
    main()
